version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: storages-postgres-1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - express-storages-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: storages-redis-1
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - express-storages-network
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:

networks:
  express-storages-network:
    driver: bridge
